/*
 Navicat Premium Dump SQL

 Source Server         : AREK
 Source Server Type    : MySQL
 Source Server Version : 50740 (5.7.40)
 Source Host           : localhost:3306
 Source Schema         : arekdb

 Target Server Type    : MySQL
 Target Server Version : 50740 (5.7.40)
 File Encoding         : 65001

 Date: 06/03/2026 17:53:10
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for summarytable
-- ----------------------------
DROP TABLE IF EXISTS `summarytable`;
CREATE TABLE `summarytable`  (
  `AREK Study Nr.` int(11) NULL DEFAULT NULL,
  `Study subject (Human, Mouse, Rat)` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `Study ID` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `Study title` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `Study type (Observational, Experimental)` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `Funding source (NIH, ERC, etc.)` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `Sample for sequencing` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `f8` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `Sample type (Blood, Organs, Biopsies, Feces, Saliva, Cells etc)` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `Collection date/time` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `Sample storage (-80 or Liquid nitrogen)` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `RNA sequencing` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `Sequencing platform` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `Sequencing method` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `Sequencing depth` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `Library prep method` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `Library prep kit/DNA extraction kit` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `Avg read length` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `Adaptor sequence` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `Single end/paried end` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `Fecal 16s sequencing` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `Metagenomic sequencing` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `Reference database/tool used for taxonomy` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of summarytable
-- ----------------------------
INSERT INTO `summarytable` VALUES (1, 'Human', 'PRJCA021196', 'Metagenomic sequencing in patients with alcohol-induced osteonecrosis of the femoral head', 'Experimental', 'National Natural Science Foundation of China, Zhejiang Provincial Natural Science Foundation, Heluo Youth Talent Promotion Project', 'Yes', NULL, 'Feces', '2021-2022', '-80', 'No', 'Illumina NovaSeq 6000', 'WGS', NULL, NULL, 'TruSeq Nano DNA LT Library Preparation Kit', NULL, NULL, 'paired end', 'No', 'Yes', 'bowtie2 (version 2.2.0)');
INSERT INTO `summarytable` VALUES (2, 'Human', 'PRJCA022064', '16S rDNA analysis in patients with alcohol-induced osteonecrosis of the femoral head', 'Experimental', 'National Natural Science Foundation of China, Zhejiang Provincial Natural Science Foundation, Heluo Youth Talent Promotion Project', 'Yes', NULL, 'Feces', '2021-2022', '-80', 'No', 'Illumina NovaSeq 6000', '16S rDNA', NULL, NULL, 'E.Z.N.A.® Stool DNA Kit', '150bp', NULL, 'paired end', 'Yes', 'No', 'bowtie2 (version 2.2.0)');
INSERT INTO `summarytable` VALUES (3, 'Human', 'PRJDB10075', 'Association between alcohol consumption and oesophageal microbiota in oesophageal squamous cell carcinoma', 'Experimental', 'National Key R&D Program of China, Medical Innovation project of Fujian Province', 'Yes', NULL, 'Cancerous', '2020', '-80', 'No', 'Illumina HiSeq 2500', '16S rRNA', NULL, NULL, 'NA', '250bp', NULL, 'NA', 'No', 'No', 'Greengenes (version 13.5)');
INSERT INTO `summarytable` VALUES (4, 'Human', 'PRJEB18041', 'Data on gut metagenomes of the patients with alcoholic dependence syndrome and alcoholic liver cirrhosis', 'Experimental', 'Ministry of Education and Science of the Russian Federation', 'Yes', NULL, 'Feces', '2015', '-20', 'No', 'SOLiD 4 platform', 'shotgun WGS', NULL, 'Paired-end DNA library construction and shotgun sequencing', 'SOLiD Fragment Library Construction Kit, SOLiD Fragment Library Barcoding Module 1–16, SOLiD EZ Bead TM E80 System Consumables and SOLiD ToP Sequencing Kit, MM50/5', '50 bp', NULL, 'paired end', 'No', 'Yes', 'NCBI');
INSERT INTO `summarytable` VALUES (5, 'Rat', 'PRJEB44965', 'Effects of alcohol binge drinking and oleoylethanolamide pretreatment in the fecal microbiota', 'Experimental', 'FEDER (European Union)/Ministerio de Ciencia e Innovación/Agencia Estatal de Investigación (Spain), Consejería de Educación, Juventud y Deporte', 'Yes', NULL, 'Feces', '2018', '-80', 'No', 'Illumina MiSeq', '16S rDNA', NULL, NULL, 'DNeasy PowerLyzer PowerSoil Kit', '300bp', NULL, 'paired end', 'Yes', 'No', 'RDP classifier and database v. 2.11');
INSERT INTO `summarytable` VALUES (6, 'Human', 'PRJNA255332', 'Alcohol and tobacco consumption affects bacterial richness in oral cavity mucosa biofilms', 'Experimental', 'Fundação Beneficente Alzira Denise Hertzog Silva (ABADHS), Fundação de Amparo à Pesquisa do Estado de s’o Paulo (FAPESP), The National Institute of Science and Technology in Oncogenomics (INCITO) and Coordenação de Aperfeiçoamento de Pessoal de Ensino Superior (CAPES). EDN and JCS are fellows of Conselho Nacional de Desenvolvimento Científico e Tecnol gico (CNPq, Brazil)', 'Yes', NULL, 'Oral', '2014', 'FTA elute cards', 'No', 'ION_TORRENT', '16S rRNA-V1', NULL, 'PCR amplicon', NULL, NULL, NULL, NULL, 'No', 'No', 'SILVA 111 SSU');
INSERT INTO `summarytable` VALUES (7, 'Human', 'PRJNA321193', 'Alterations in oral bacterial communities are associated with risk factors for oral and oropharyngeal cancer', 'Experimental', NULL, 'Yes', NULL, 'Oral', '2011', '-80', 'No', 'Illumina MiSeq v2', '16S rRNA-V4', NULL, NULL, 'QIAsymphony Virus/Bacteria Midi Kit', '150bp', NULL, 'single end', 'No', 'No', 'Greengenes 13.5');
INSERT INTO `summarytable` VALUES (8, 'Human', 'PRJNA378267', 'The respiratory tract microbial biogeography in alcohol use disorder', 'Experimental', 'NIAAA,National Heart Lung and Blood Institute, NIH, National Institute of General Medical', 'Yes', NULL, 'Oral', '2013', '-80', 'No', 'Illumina MiSeq', '16S rRNA-V3-V4', NULL, 'Gene-specific primers with Illumina adapters and molecular barcodes', 'QIAamp DNA Stool Mini Kit', '300bp', 'Forward adapter: 5′-AATGATACGGCGACCACCGAGATCTACAC-3′, Reverse adapter: 5′-CAAGCAGAAGACGGCATACGAGAT-3′', 'paired end', 'No', 'No', 'GreenGenes 13.5');
INSERT INTO `summarytable` VALUES (9, 'Mouse', 'PRJNA384576', 'Alcohol-associated intestinal dysbiosis impairs pulmonary host defense against Klebsiella pneumoniae', 'Experimental', NULL, 'Yes', NULL, 'Feces', '2016', '-80', 'No', 'Illumina MiSeq', '16S rRNA-V3-V4', NULL, 'Gene-specific primers with Illumina adapters and molecular barcodes', 'QIAamp DNA Stool Mini Kit（Qiagen）', '300bp', NULL, 'single end', 'Yes', 'No', 'UCHIME');
INSERT INTO `summarytable` VALUES (10, 'Rat', 'PRJNA417868', 'Effects of moderate, voluntary ethanol consumption on the rat and human gut microbiome', 'Experimental', 'NIH', 'Yes', NULL, 'Feces', '2014', '-80', 'No', 'Illumina MiSeq', '16S rRNA-V4', NULL, 'Universal primers 515F/806R', 'MoBio PowerSoil', '300bp', NULL, 'paired end', 'Yes', 'No', 'Greengenes');
INSERT INTO `summarytable` VALUES (11, 'Human', 'PRJNA434312', 'Human oral microbiome and prospective risk for pancreatic cancer: a population-based nested case-control study', 'Experimental', 'NCI', 'Yes', NULL, 'Oral', NULL, '-80', 'No', 'Roche 454 FLX Titanium', '16S rRNA-V3-V4', '11782(9,354,571 high-quality 16S reads in total), mean 11,782 (SD 2,799) sequences per sample', NULL, 'MoBio PowerSoil DNA Isolation Kit', NULL, NULL, 'single end', 'No', 'No', 'Human Oral Microbiome Database (HOMD)');
INSERT INTO `summarytable` VALUES (12, 'Human', 'PRJNA482931', 'Impacts of Maternal Diet and Alcohol Consumption during Pregnancy on Maternal and Infant Gut Microbiota', 'Experimental', 'Research Ethics Boards of Medical School of Wuhan University ', 'Yes', NULL, 'Feces', '2017', '-80', 'No', 'Illumina MiSeq', '16S rRNA-V3-V4', '50,000 reads per sample', 'primers 338F', 'E.Z.N.A.® Soil DNA Kit', '300bp', NULL, 'paired end', 'Yes', 'No', 'SILVA 123 SSU');
INSERT INTO `summarytable` VALUES (13, 'Mouse', 'PRJNA487067', 'Alcohol consumption increases susceptibility to pneumococcal pneumonia in a humanized murine HIV model mediated by intestinal dysbiosis', 'Experimental', 'NIH,NIAAA', 'Yes', NULL, 'Feces', '2017', NULL, 'No', 'Illumina MiSeq', '16S rRNA-V4', 'Median sequencing depth: 24,740 reads; minimum: 2,409 reads; maximum: 35,241 reads', 'Gene-specific primers with Illumina adapters and molecular barcodes', 'QIAamp DNA Stool Mini Kit', '250bp', NULL, 'paired end', 'Yes', 'No', 'SILVA 132 SSU');
INSERT INTO `summarytable` VALUES (14, 'Human', 'PRJNA503710', 'Alterations in the gut microbiome and metabolism with coronary artery disease severity', 'Experimental', 'National Natural Science Foundation of China, the CAMS Innovation Fund for Medical Sciences (CIFMS),  the CAMS Innovation Fund for Medical Sciences', 'Yes', NULL, 'Feces', '2017', '-80', 'No', 'Illumina MiSeq', '16S rRNA-V4', '10,800 sequences per sample', 'PCR amplicon', NULL, '300bp', NULL, 'paired end', 'Yes', 'No', 'RDP database version 11.5');
INSERT INTO `summarytable` VALUES (15, 'Human', 'PRJNA520863', 'Inflammatory Biomarkers, Microbiome, Depression, and Executive Dysfunction in Alcohol Users', 'Experimental', 'National Institute on Minority Health and Health Disparities', 'Yes', NULL, 'Saliva', NULL, '-85', 'No', 'Illumina MiSeq', '16S rRNA-V3-V4', NULL, 'FastStart PCR master mix (Roche) and primer pair', 'Illumina Nextera DNA preparation kit/QIAGEN blood DNA extraction kit', NULL, NULL, 'paired end', 'No', 'No', NULL);
INSERT INTO `summarytable` VALUES (16, 'Human', 'PRJNA522306', 'Colonizing multidrug-resistant bacteria and the longitudinal evolution of the intestinal microbiome after liver transplantation', 'Experimental', 'NIH', 'Yes', NULL, 'Feces', '2014-2017', '-80', 'No', 'Illumina MiSeq or Illumina HiSeq', '16S rRNA-V3-V4', '7,500 counts per sample', 'Illumina Nextera adaptors', 'Illumina Nextera XT Index kits/MagAttract PowerSoil DNA Kit', '300bp', NULL, 'paired end', 'Yes', 'No', 'Greengenes 97% database');
INSERT INTO `summarytable` VALUES (17, 'Mouse/Human', 'PRJNA525701', 'Bacteriophage targeting of gut bacterium attenuates alcoholic liver disease', 'Experimental', 'AASLD Pinnacle Research Award in Liver Disease and a pilot project award from Southern California Research Center for Alcoholic Liver and Pancreatic Disease (ALPD) and Cirrhosis, National Institute of General Medical Sciences (NIGMS)–NIH Chemistry–Biology Interface Training Grant, Biocodex Microbiota Foundation Grant,NIH, Biomedical Laboratory Research & Development Service of the VA Office of Research and Development, Wellcome Trust', 'Yes', NULL, 'Feces', '2018', NULL, 'No', 'Illumina MiSeq', '16S rRNA-V4', NULL, 'PCR amplicon', 'QIAamp Fast DNA Stool kit', '250 bp', NULL, 'paired end', 'Yes', 'No', 'MOTHUR');
INSERT INTO `summarytable` VALUES (18, 'Human', 'PRJNA529415', NULL, 'Experimental', NULL, 'Yes', NULL, 'Feces, Saliva', '2018', NULL, 'No', 'Illumina MiSeq', '16S rRNA', NULL, NULL, NULL, '150bp', NULL, 'paired end', NULL, NULL, NULL);
INSERT INTO `summarytable` VALUES (19, 'Mouse/Human', 'PRJNA553184', 'Gut Microbiota-Induced Changes in β-Hydroxybutyrate Metabolism Are Linked to Altered Sociability and Depression in Alcohol Use Disorder', 'Experimental', 'Belgium National Scientific Research Fund, UCLouvain, Funds Baillet Latour, FRFS-WELBIO, Wallonia', 'Yes', NULL, 'Feces', '2017', '-80', 'No', 'Illumina MiSeq', '16S rRNA-V5-V6', '157,737 pass-filter reads per sample', NULL, 'QIAamp DNA Stool Mini Kit (QIAGEN, Germany)', '300bp', NULL, 'paired end', 'Yes', 'No', 'RDP database version 1.1');
INSERT INTO `summarytable` VALUES (20, 'Mouse', 'PRJNA555778', 'New strain of Pediococcus pentosaceus alleviates ethanol-induced liver injury by modulating the gut microbiota and short-chain fatty acid metabolism', 'Experimental', NULL, 'Yes', NULL, 'Feces', '2018', '-80', 'No', 'Illumina MiSeq', '16S rRNA-V3-V4', NULL, '341F and 806R primers', 'QIAamp Fast DNA Stool Mini Kit', NULL, NULL, 'paired end', 'Yes', 'No', 'Greengenes');
INSERT INTO `summarytable` VALUES (21, 'Rat', 'PRJNA543718', 'Beneficial effects of LRP6-CRISPR on prevention of alcohol-related liver injury surpassed fecal microbiota transplant in a rat model', 'Experimental', 'Natural Science Foundation of Zhejiang Province, Key medical discipline in Jiaxing—Infectious disease, Key medical discipline in Jiaxing –Gastroenterology', 'Yes', NULL, 'Feces', '2019', '-80', 'No', 'Illumina MiSeq', '16S rRNA-V3-V4', NULL, '338F / 806R', 'Power Fecal DNA Kit (QIAamp)', NULL, NULL, 'single end', 'Yes', 'No', 'SLIVA  128 SSU');
INSERT INTO `summarytable` VALUES (22, 'Mouse', 'PRJNA592297', 'Bifidobacterium breve ATCC15700 pretreatment prevents alcoholic liver disease through modulating gut microbiota in mice exposed to chronic alcohol intake', 'Experimental', 'National Natural Science Foundation of China, Gansu Province Major Science and Technology projects, Gansu Province Foundation for Distinguished Young Scholars', 'Yes', NULL, 'Feces', '2017', '-80', 'No', 'Illumina MiSeq', '16S rRNA-V4-V5', NULL, '515F/909R', 'DNA extraction kit (Tiangen Biotech, Shanghai, China)', NULL, NULL, 'single end', 'Yes', 'No', 'RDP classifier');
INSERT INTO `summarytable` VALUES (23, 'Human', 'PRJNA604280', 'Alcohol Use Is Associated With Intestinal Dysbiosis and Dysfunctional CD8+ T-Cell Phenotypes in Persons With Human Immunodeficiency Virus', 'Observational', 'NIAAA, National Institute of General Medical Sciences', 'Yes', NULL, 'Feces', '2018', '-80', 'No', 'Illumina MiSeq V2', '16S rRNA-V4', NULL, 'PCR amplification of 16S V4 with modified 515F/806R', NULL, NULL, NULL, 'paired end', 'Yes', 'No', 'SILVA 132 SSU ');
INSERT INTO `summarytable` VALUES (24, 'Human', 'PRJNA613834', 'Functional Microbial Responses to Alcohol Abstinence in Patients With Alcohol Use Disorder', 'Experimental', 'NIH ', 'Yes', NULL, 'Feces', '2020', NULL, 'No', 'Illumina HiSeq 4000', 'WGS', NULL, NULL, 'FastDNA Spin Kit（MP-Biomedicals）', '150bp', NULL, 'paired end', 'No', 'Yes', 'MetaPhlAn2 version 2.7.7');
INSERT INTO `summarytable` VALUES (25, 'Human', 'PRJNA634528', 'Longitudinal gut microbiome changes in alcohol use disorder are influenced by abstinence and drinking quantity', 'Experimental', NULL, 'Yes', NULL, 'Oral', '2018', '-80', 'No', 'Ion Torrent S5 XL semiconductor sequencer', '16S rRNA', '150,000 reads per sample', NULL, 'PowerMag Microbiome RNA/DNA isolation kit', NULL, NULL, 'paired end', 'No', 'No', 'USEARCH v11');
INSERT INTO `summarytable` VALUES (26, 'Mouse', 'PRJNA640138', 'Chronic stress and corticosterone exacerbate alcohol-induced tissue injury in the gut-liver-brain axis', 'Experimental', 'NIH', 'Yes', NULL, 'Feces', '2019', NULL, 'No', 'Illumina MiSeq', '16S rRNA', NULL, NULL, NULL, NULL, NULL, 'single end', 'Yes', 'No', 'RDP classifier, GreenGenes');
INSERT INTO `summarytable` VALUES (27, 'Human', 'PRJNA698746', 'Alterations in gut microbiota of esophageal squamous cell carcinoma patients', 'Experimental', 'Hong Kong Innovation and Technology Fund', 'Yes', NULL, 'Feces', '2020', '-80', 'No', 'Illumina MiSeq', '16S rRNA-V3-V4', NULL, NULL, 'QIAamp Fast DNA Stool Mini Kit', '300bp', NULL, 'paired end', 'Yes', 'No', 'SILVA 132 SSU ');
INSERT INTO `summarytable` VALUES (28, 'Human', 'PRJNA734860', 'Bile Acid Changes Associated With Liver Fibrosis and Steatosis in the Mexican-American Population of South Texas', 'Experimental', 'MD Anderson Cancer Center Support Grant, CPRIT Research Training Grant Award', 'Yes', NULL, 'Feces', '2018-2020', '-80', 'No', 'Illumina MiSeq', '16S rRNA-V4', NULL, NULL, 'QIAamp Fast DNA Stool Mini Kit', '250 bp', NULL, 'paired end', 'Yes', 'YES(in the datasets', 'SILVA');
INSERT INTO `summarytable` VALUES (29, 'Human', 'PRJNA895096', 'Diurnal changes of the oral microbiome in patients with alcohol dependence', 'Experimental', 'National Clinical Research Center for Mental Disorders, National Key R&D Program of China, National Natural Science Foundation of China', 'Yes', NULL, 'Saliva', '2019', '-80', 'No', 'Illumina HiSeq 2500', '16S rRNA-V4', NULL, '515F/806R', NULL, '250 bp', NULL, 'paired end', 'No', 'No', 'RDP Classifier v.2.2');
INSERT INTO `summarytable` VALUES (30, 'Human', 'PRJNA905862', 'Disrupted diurnal oscillations of the gut microbiota in patients with alcohol dependence', 'Experimental', 'National Natural Science Foundation of China', 'Yes', NULL, 'Feces', '2019', '-80', 'No', 'Illumina HiSeq 2500', '16S rRNA-V4', NULL, NULL, 'MagPure Stool DNA KF Kit B', '250 bp', NULL, 'paired end', 'Yes', 'No', 'RDP classifer v2.2');
INSERT INTO `summarytable` VALUES (31, 'Human', 'PRJNA909793', 'Variety of Fruit and Vegetables and Alcohol Intake are Associated with Gut Microbial Species and Gene Abundance in Colorectal Cancer Survivors', 'Experimental', NULL, 'Yes', NULL, 'Feces', '2019', '-80', 'No', 'Illumina MiSeq, NovaSeq 6000', '16S rRNA-V4, WGS', NULL, '515F/806R', NULL, '250–270 bp', NULL, 'paired end', 'Yes', 'No', 'HUMAnN3');
INSERT INTO `summarytable` VALUES (32, 'Mouse', 'PRJNA918387', 'TRPV6 deficiency attenuates stress and corticosterone-mediated exacerbation of alcohol-induced gut barrier dysfunction and systemic inflammation', 'Experimental', 'NIH', 'Yes', NULL, 'Feces', '2019', NULL, 'No', 'Illumina MiSeq', '16S rRNA-V4-V5', NULL, NULL, NULL, NULL, NULL, 'single end', 'Yes', 'No', 'GreenGenes');
INSERT INTO `summarytable` VALUES (33, 'Mouse', 'PRJNA1044232', 'Lacticaseibacillus rhamnosus LRa05 alleviated liver injury in mice with alcoholic fatty liver disease by improving intestinal permeability and balancing gut microbiota', 'Experimental', 'Education Department of Henan Province', 'Yes', NULL, 'Feces', '2023', '-80', 'No', 'Illumina MiSeq', '16S rRNA-V3-V4', NULL, NULL, 'FastDNA SPIN Kit', '300bp', NULL, 'paired end', 'Yes', 'No', 'RDP database v18');
INSERT INTO `summarytable` VALUES (34, 'Mouse', 'PRJNA1140604(RNA)', 'Intestinal microbiota homeostasis analysis in riboflavin-treated alcoholic liver disease', 'Experimental', 'National Natural Science Foundation of China, Natural Science Foundation of Heilongjiang Province, Heilongjiang Postdoctoral Science Foundation', 'Yes', NULL, 'Liver', NULL, NULL, 'Yes', 'Illumina NovaSeq 6000', 'RNA', NULL, NULL, 'TRIzol Reagent', '150 bp', NULL, 'paired end', 'No', 'No', NULL);
INSERT INTO `summarytable` VALUES (35, 'Mouse', 'PRJNA1141499', 'Intestinal microbiota homeostasis analysis in riboflavin-treated alcoholic liver disease', 'Experimental', 'National Natural Science Foundation of China, Natural Science Foundation of Heilongjiang Province, Heilongjiang Postdoctoral Science Foundation', 'Yes', NULL, 'Feces', NULL, NULL, 'Yes', 'Illumina NovaSeq 6000', '16S rRNA-V3-V4', NULL, '341F/806R', 'HiPure Stool DNA Kit', '250 bp', NULL, 'paired end', 'Yes', 'No', NULL);
INSERT INTO `summarytable` VALUES (36, 'Human', 'PRJNA597697', 'The effects of cigarettes and alcohol on intestinal microbiota in healthy men', 'Experimental', 'Natural Science Foundation of Zhejiang Province, Science and Technology  Plan of Medicine and Health of Zhejiang Province, Public Welfare Technology Application Research Plan of Zhejiang Province', 'Yes', NULL, 'Feces', '2017-2019', '-80', 'No', 'Illumina MiSeq', '16S rRNA-V3-V4', NULL, '338F/806R', 'TIANamp Stool DNA Kit', '300bp', NULL, 'paired end', 'Yes', 'No', 'SILVA 128 SSU ');

SET FOREIGN_KEY_CHECKS = 1;
